### ISSUE TITLE
Donation proposal: jabba-wrapper

### ISSUE THREAD

**Issue by nicerloop** [Jabba-Team/jabba#15]
Hi,

I am the author of jabba-wrapper (https://github.com/nicerloop/jabba-wrapper) which is heavily dependent on and uses script code from the jabba project.
I would gladly contribute these scripts to the jabba project, if there is interrest.

What do you think?

**Comment by patrick-mccourt** [comment]
Hi @nicerloop sorry for the slow reply but I think the wrapper would be a great addition to the project, definitely can see the benefits. If you were willing to open a pull request to add the wrapper scripts to the repo we can get it added.

**Comment by nicerloop** [comment]
PR submitted.

**Comment by nicerloop** [comment]
@patrick-mccourt have you had any time to review the PR? Any comments?
For now it is a separate set of scripts relying on the install scripts, but they may be merged to the install scripts.

**Comment by patrick-mccourt** [comment]
Hi @nicerloop 

I haven't had a chance to review just yet. I can take a look this weekend but feel free to review sooner if you can

**Comment by nicerloop** [comment]
> Hi @nicerloop [...] feel free to review sooner if you can

As the author of the PR, I cannot review my own work. Can you have a look ?

**Comment by patrick-mccourt** [comment]
Hi @nicerloop apologies, I somehow missed you were the PR Author, I've had a look and happy for it to be merged as is. We can maybe look at refactoring the scripts at a later date. I am doing a bit of work on the build process and will look at merging the two open PRs next

**Comment by nicerloop** [comment]
Hi, any news?

**Comment by patrick-mccourt** [comment]
Hi @nicerloop as you can see I've reappeared and started working on jabba again, I've just pushed out 0.13.0 which includes your wrapper changes
Closed by  #23
