### ISSUE TITLE
Move the index.json to another repository

### ISSUE THREAD

**Issue by martonsz** [Jabba-Team/jabba#18]
Can we move the index.json to another repository? And run the auto-update there?

I feel that the auto commits are a bit annoying when browsing the Git tree. Because there are so many :-/
I'm talking about these ones: [daily update for the index file](https://github.com/Jabba-Team/jabba/commit/fea6ba1152005804eb6a905e0dc8f2d4647682f2)

I can try doing it if I get access to this account :D

**Comment by patrick-mccourt** [comment]
We could just load it from the jabba-index repo I suppose

**Comment by martonsz** [comment]
That is a bit better. But then it will start to be in the way of the source code commits for that repo.
It would be best to have the index file on a separate repo where the commit history is only about the index file.

**Comment by patrick-mccourt** [comment]
Yes good point. I have done a bit of re-arranging and the index now lives in https://github.com/Jabba-Team/index and the generator repo is now called https://github.com/Jabba-Team/index-generator, just to make it clear which is which. 

0.12.1 is now fully released too which includes the M1 release, and will point to this new location
