### ISSUE TITLE
No Darwin entries in the new index

### ISSUE THREAD

**Issue by p-linnane** [Jabba-Team/jabba#21]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project.

While packaging jabba 0.12.1 we encountered failures during testing. It appears this is due to the [new index](https://raw.githubusercontent.com/Jabba-Team/index/main/index.json) not containing any entires for Darwin (macOS).

Related to https://github.com/Homebrew/homebrew-core/pull/123572

**Comment by patrick-mccourt** [comment]
Apologies, I made a silly error when updating the index generator. Fixing it now

**Comment by patrick-mccourt** [comment]
Hi @p-linnane, this has been fixed now, I had commented windows and mac from the script when looking into an issue with linux jdks, and forgot to uncomment them. Have restored and run the index manually now so they're all back.

**Comment by p-linnane** [comment]
Thank you! Confirming everything is working as expected.
