### ISSUE TITLE
Add the possibility to execute some script after some commands

### ISSUE THREAD

**Issue by CelesteGH** [Jabba-Team/jabba#28]
If we could execute a script after a command we could ,for exemple, have it switch java globally or have stuff like Auto-env do stuff.

**Comment by patrick-mccourt** [comment]
Sure, can you give me an example of the kinds of commands you'd do? 

It might be that a wrapper script that runs your commands and your version switch for you is the way to go but I'd like to understand your workflow.

**Comment by patrick-mccourt** [comment]
Closing this issue as the ask is unclear
