### ISSUE TITLE
Highlight Current version during jabba ls

### ISSUE THREAD

**Issue by CelesteGH** [Jabba-Team/jabba#29]
nvm combines ls and current into ls by simply adding a * on the left of the version used : 

nvm ls

  * 14.21.2 (Currently using 64-bit executable)
    12.16.3
    9.4.0

This feels way more efficient.

**Comment by patrick-mccourt** [comment]
I see, would that give similar output to java --version?

**Comment by patrick-mccourt** [comment]
I understand now, as ls prints out the installed versions, when it gets to current, highlight it somehow to show that is current.
