### ISSUE TITLE
Take Ownership of Homebrew package

### ISSUE THREAD

**Issue by patrick-mccourt** [Jabba-Team/jabba#4]
https://formulae.brew.sh/formula/jabba

**Comment by nicerloop** [comment]
see https://github.com/Homebrew/homebrew-core/pull/119263

**Comment by nicerloop** [comment]
This would require a formal statement from the original owner/project, or sufficient time and reputation to build up.
https://github.com/Homebrew/homebrew-core/pull/119263#discussion_r1058403931

**Comment by patrick-mccourt** [comment]
Thanks @nicerloop for starting this, I'll see if I can get a response on the original repo owner to confirm the new project.

**Comment by nicerloop** [comment]
Done: of https://github.com/Homebrew/homebrew-core/pull/119263
