### ISSUE TITLE
Unable to download java using jabba install

### ISSUE THREAD

**Issue by soham-slp** [Jabba-Team/jabba#47]
I have set JABBA_HOME as G:\Jabba, My Jabba is installed here, but when I try to download any jdk version I get this error. This is latest as I installed jabba just yesterday

```
Downloading openjdk@8.0.342 (https://api.foojay.io/disco/v3.0/ids/0527f23dc3c86f284781cd7b5c0d1646/redirect)
41214623/41214623
Extracting C:\Users\MYPC~1\AppData\Local\Temp\jabba-d-3266386429 to G:\Jabba\jdk\openjdk@8.0.342
G:\Jabba\jdk\openjdk@8.0.342\bin\java.exe wasn't found. If you believe this is an error - please create a ticket at https://github.com/Jabba-Team/jabba/issues (specify OS and command that was used)
```

Jabba version
```bash
jabba --version
0.14.0
```

Note:
I may have found something, turns out that the downloaded file C:\Users\MYPC~1\AppData\Local\Temp\jabba-d-3266386429 has no extension

**Comment by patrick-mccourt** [comment]
hi @soham-slp,

I've had a quick look and the issue seems to be with the index, I'm assuming from your log above you're running jabba install openjdk@8? The index generator seems to have updated that download url about 3 months ago, however the new link is not the correct one. I will investigate what's wrong with the generator and get back to you.

**Comment by soham-slp** [comment]
> hi @soham-slp,
> 
> I've had a quick look and the issue seems to be with the index, I'm assuming from your log above you're running jabba install openjdk@8? The index generator seems to have updated that download url about 3 months ago, however the new link is not the correct one. I will investigate what's wrong with the generator and get back to you.

**Comment by soham-slp** [comment]
Hey @patrick-mccourt  yes I am doing
```bash
jabba install openjdk@8.0.342
```

It is just not openjdk, oracle, oracle_openjdk all don't work properly

**Comment by patrick-mccourt** [comment]
This should now be working, was fixed upstream in discoapi and has now fed through into the jabba index
