### ISSUE TITLE
1.8.0_431 is not an acceptable version

### ISSUE THREAD

**Issue by ren-142326** [Jabba-Team/jabba#51]
###  "_" This character does not seem to pass the version number specification check,
![image](https://github.com/user-attachments/assets/3fc93c2d-26b7-4225-aedb-e462b6905e8d)

###  When I replace "_" with "-", the version number is verified,
![image](https://github.com/user-attachments/assets/783a07b6-0dcf-4ddd-941b-fbe10d987c2a)

###  But java -version outputs 1.8.0_431
![image](https://github.com/user-attachments/assets/8df7929b-4110-4c1f-b08c-de50566ad225)

###  So I hope "_" is also the correct version number character

**Comment by patrick-mccourt** [comment]
the semver package deals with version parsing, and _ isn't accepted by semver
